-- G12 AI Hub — Supabase setup
-- Run this entire script once in Supabase > SQL Editor.

create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  subject text not null,
  type text not null,
  title text not null,
  file_name text not null,
  file_path text not null unique,
  file_url text not null,
  created_at timestamptz not null default now()
);

alter table public.materials enable row level security;

drop policy if exists "Public can read materials" on public.materials;
create policy "Public can read materials"
on public.materials for select
to anon, authenticated
using (true);

drop policy if exists "Public can add materials" on public.materials;
create policy "Public can add materials"
on public.materials for insert
to anon, authenticated
with check (
  subject in ('Structured Programming','Physics II','Analytical Geometry & Calculus I','University Requirement (1)','University Elective (1)','University Elective (2)')
  and type in ('Lecture','Assignment','Quiz','Experiment','Summary / Notes')
);

-- Create the public storage bucket used by the website.
insert into storage.buckets (id, name, public)
values ('g12-materials', 'g12-materials', true)
on conflict (id) do update set public = true;

-- Anyone can view files in this public bucket.
drop policy if exists "Public can read G12 materials" on storage.objects;
create policy "Public can read G12 materials"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'g12-materials');

-- Anyone using the public website can upload PDF files to this bucket.
drop policy if exists "Public can upload G12 PDFs" on storage.objects;
create policy "Public can upload G12 PDFs"
on storage.objects for insert
to anon, authenticated
with check (
  bucket_id = 'g12-materials'
  and lower(storage.extension(name)) = 'pdf'
);
